# Generated by Django 3.0.8 on 2020-10-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spark',
            new_name='payment',
        ),
    ]
