# Generated by Django 3.0.8 on 2020-10-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201005_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
