# Generated by Django 3.0.8 on 2020-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_sparks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparks',
            name='email',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
