# Generated by Django 3.0.8 on 2020-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_sparks_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sparks',
        ),
    ]
